export interface CNAEItem {
  codigo: string;
  descricao: string;
}

export const CNAE: CNAEItem[] = [
  // Seção F — Construção
  { codigo: '4110-7/00', descricao: 'Incorporação de empreendimentos imobiliários' },
  { codigo: '4120-4/00', descricao: 'Construção de edifícios' },
  { codigo: '4211-1/01', descricao: 'Construção de rodovias e ferrovias' },
  { codigo: '4299-5/99', descricao: 'Outras obras de engenharia civil não especificadas' },
  { codigo: '4321-5/00', descricao: 'Instalação e manutenção elétrica' },
  { codigo: '4322-3/01', descricao: 'Instalações hidráulicas, sanitárias e de gás' },
  { codigo: '4330-4/01', descricao: 'Impermeabilização em obras de engenharia civil' },
  { codigo: '4391-6/00', descricao: 'Obras de fundações' },
  { codigo: '4399-1/03', descricao: 'Obras de alvenaria' },
  // Seção J — Informação e Comunicação
  { codigo: '5811-5/00', descricao: 'Edição de livros' },
  { codigo: '5812-3/00', descricao: 'Edição de jornais' },
  { codigo: '5813-1/00', descricao: 'Edição de revistas' },
  { codigo: '5820-2/00', descricao: 'Edição integrada à impressão de livros, jornais, revistas e outras publicações' },
  { codigo: '5911-1/01', descricao: 'Estúdios cinematográficos' },
  { codigo: '5912-0/01', descricao: 'Serviços de dublagem' },
  { codigo: '5920-1/00', descricao: 'Atividades de gravação de som e edição de música' },
  { codigo: '6110-8/01', descricao: 'Serviços de telefonia fixa comutada - STFC' },
  { codigo: '6120-5/01', descricao: 'Telefonia móvel celular' },
  { codigo: '6190-6/01', descricao: 'Provedores de acesso às redes de comunicações' },
  { codigo: '6201-5/00', descricao: 'Desenvolvimento de programas de computador sob encomenda' },
  { codigo: '6202-3/00', descricao: 'Desenvolvimento e licenciamento de programas de computador customizáveis' },
  { codigo: '6203-1/00', descricao: 'Desenvolvimento e licenciamento de programas de computador não-customizáveis' },
  { codigo: '6204-0/00', descricao: 'Consultoria em tecnologia da informação' },
  { codigo: '6209-1/00', descricao: 'Suporte técnico, manutenção e outros serviços em tecnologia da informação' },
  { codigo: '6311-9/00', descricao: 'Tratamento de dados, provedores de serviços de aplicação e serviços de hospedagem na internet' },
  { codigo: '6319-4/00', descricao: 'Portais, provedores de conteúdo e outros serviços de informação na internet' },
  { codigo: '6391-7/00', descricao: 'Agências de notícias' },
  { codigo: '6399-2/00', descricao: 'Outras atividades de prestação de serviços de informação não especificadas' },
  // Seção K — Atividades Financeiras
  { codigo: '6411-3/00', descricao: 'Banco Central' },
  { codigo: '6421-2/00', descricao: 'Bancos comerciais' },
  { codigo: '6422-1/00', descricao: 'Bancos múltiplos com carteira comercial' },
  { codigo: '6431-0/00', descricao: 'Bancos múltiplos sem carteira comercial' },
  { codigo: '6435-2/01', descricao: 'Sociedades de crédito imobiliário' },
  { codigo: '6450-6/00', descricao: 'Sociedades de capitalização' },
  { codigo: '6461-1/00', descricao: 'Holdings de instituições financeiras' },
  { codigo: '6499-8/01', descricao: 'Clubes de investimento' },
  { codigo: '6511-1/01', descricao: 'Sociedades seguradoras de vida' },
  { codigo: '6521-8/00', descricao: 'Resseguros' },
  { codigo: '6530-8/00', descricao: 'Previdência complementar fechada' },
  { codigo: '6611-8/01', descricao: 'Bolsa de valores' },
  { codigo: '6621-5/01', descricao: 'Peritos e avaliadores de seguros' },
  { codigo: '6622-3/00', descricao: 'Corretores e agentes de seguros, de planos de previdência complementar e de saúde' },
  { codigo: '6630-4/00', descricao: 'Atividades de administração de fundos por contrato ou comissão' },
  // Seção L — Atividades Imobiliárias
  { codigo: '6810-2/01', descricao: 'Compra e venda de imóveis próprios' },
  { codigo: '6821-8/01', descricao: 'Corretagem na compra e venda e avaliação de imóveis' },
  { codigo: '6821-8/02', descricao: 'Corretagem no aluguel de imóveis' },
  { codigo: '6822-6/00', descricao: 'Gestão e administração da propriedade imobiliária' },
  // Seção M — Atividades Profissionais, Científicas e Técnicas
  { codigo: '6910-9/00', descricao: 'Atividades jurídicas, exceto cartórios' },
  { codigo: '6911-7/01', descricao: 'Serviços advocatícios' },
  { codigo: '6912-5/00', descricao: 'Atividades auxiliares da justiça' },
  { codigo: '6920-6/01', descricao: 'Atividades de contabilidade' },
  { codigo: '6920-6/02', descricao: 'Atividades de consultoria e auditoria contábil e tributária' },
  { codigo: '7010-6/00', descricao: 'Sedes de empresas e unidades administrativas locais' },
  { codigo: '7020-3/00', descricao: 'Atividades de consultoria em gestão empresarial' },
  { codigo: '7111-1/00', descricao: 'Serviços de arquitetura' },
  { codigo: '7112-0/00', descricao: 'Serviços de engenharia' },
  { codigo: '7119-7/01', descricao: 'Serviços de cartografia, topografia e geodesia' },
  { codigo: '7119-7/02', descricao: 'Atividades de estudos geológicos' },
  { codigo: '7119-7/99', descricao: 'Atividades técnicas relacionadas à engenharia e arquitetura não especificadas' },
  { codigo: '7120-1/00', descricao: 'Testes e análises técnicas' },
  { codigo: '7210-0/00', descricao: 'Pesquisa e desenvolvimento experimental em ciências físicas e naturais' },
  { codigo: '7220-7/00', descricao: 'Pesquisa e desenvolvimento experimental em ciências sociais e humanas' },
  { codigo: '7311-4/00', descricao: 'Agências de publicidade' },
  { codigo: '7312-2/00', descricao: 'Agenciamento de espaços para publicidade' },
  { codigo: '7319-0/01', descricao: 'Criação de estandes para feiras e exposições' },
  { codigo: '7319-0/02', descricao: 'Promoção de vendas' },
  { codigo: '7319-0/03', descricao: 'Marketing direto' },
  { codigo: '7319-0/04', descricao: 'Consultoria em publicidade' },
  { codigo: '7320-3/00', descricao: 'Pesquisas de mercado e de opinião pública' },
  { codigo: '7410-2/01', descricao: 'Design gráfico' },
  { codigo: '7410-2/02', descricao: 'Design de produto' },
  { codigo: '7420-0/01', descricao: 'Atividades de produção de fotografias' },
  { codigo: '7490-1/01', descricao: 'Serviços de tradução, interpretação e similares' },
  { codigo: '7490-1/02', descricao: 'Escafandria e mergulho' },
  { codigo: '7490-1/03', descricao: 'Serviços de agronomia e de consultoria às atividades agrícolas e pecuárias' },
  { codigo: '7490-1/04', descricao: 'Atividades de intermediação e agenciamento de serviços e negócios em geral' },
  { codigo: '7490-1/99', descricao: 'Outras atividades profissionais, científicas e técnicas não especificadas' },
  { codigo: '7500-1/00', descricao: 'Atividades veterinárias' },
  // Seção N — Atividades Administrativas
  { codigo: '7711-0/00', descricao: 'Locação de automóveis sem condutor' },
  { codigo: '7719-5/01', descricao: 'Locação de embarcações sem tripulação' },
  { codigo: '7721-7/00', descricao: 'Aluguel de equipamentos recreativos e esportivos' },
  { codigo: '7722-5/00', descricao: 'Aluguel de fitas de vídeo, DVDs e similares' },
  { codigo: '7729-2/01', descricao: 'Aluguel de aparelhos de jogos eletrônicos' },
  { codigo: '7731-4/00', descricao: 'Aluguel de máquinas e equipamentos agrícolas sem operador' },
  { codigo: '7733-1/00', descricao: 'Aluguel de máquinas e equipamentos para construção sem operador' },
  { codigo: '7739-0/03', descricao: 'Aluguel de palcos, coberturas e outras estruturas de uso temporário' },
  { codigo: '7740-3/00', descricao: 'Gestão de ativos intangíveis não-financeiros' },
  { codigo: '7810-8/00', descricao: 'Seleção e agenciamento de mão-de-obra' },
  { codigo: '7820-5/00', descricao: 'Locação de mão-de-obra temporária' },
  { codigo: '7830-2/00', descricao: 'Fornecimento e gestão de recursos humanos para terceiros' },
  { codigo: '7911-2/00', descricao: 'Agências de viagens' },
  { codigo: '7912-1/00', descricao: 'Operadores turísticos' },
  { codigo: '7990-2/00', descricao: 'Serviços de reservas e outros serviços de turismo não especificados' },
  { codigo: '8010-1/01', descricao: 'Atividades de vigilância e segurança privada' },
  { codigo: '8011-1/01', descricao: 'Transporte de valores' },
  { codigo: '8012-9/00', descricao: 'Atividades de telemonitoramento' },
  { codigo: '8020-0/01', descricao: 'Atividades de monitoramento de sistemas de segurança eletrônico' },
  { codigo: '8111-7/00', descricao: 'Serviços combinados para apoio a edifícios, exceto condomínios prediais' },
  { codigo: '8112-5/00', descricao: 'Condomínios prediais' },
  { codigo: '8121-4/00', descricao: 'Limpeza em prédios e em domicílios' },
  { codigo: '8122-2/00', descricao: 'Imunização e controle de pragas urbanas' },
  { codigo: '8129-0/00', descricao: 'Atividades de limpeza não especificadas' },
  { codigo: '8130-3/00', descricao: 'Atividades paisagísticas' },
  { codigo: '8211-3/00', descricao: 'Serviços combinados de escritório e apoio administrativo' },
  { codigo: '8219-9/01', descricao: 'Fotocopiadoras e serviços de preparação de documentos' },
  { codigo: '8219-9/02', descricao: 'Digitação de dados' },
  { codigo: '8220-2/00', descricao: 'Atividades de teleatendimento' },
  { codigo: '8230-0/01', descricao: 'Serviços de organização de feiras, congressos e outros eventos' },
  { codigo: '8291-1/00', descricao: 'Atividades de cobrança e informações cadastrais' },
  { codigo: '8292-0/00', descricao: 'Envasamento e empacotamento sob contrato' },
  { codigo: '8299-7/01', descricao: 'Medição de consumo de energia elétrica, gás e água' },
  { codigo: '8299-7/02', descricao: 'Emissão de vales-alimentação, vales-transporte e similares' },
  { codigo: '8299-7/99', descricao: 'Outras atividades de serviços prestados às empresas não especificadas' },
  // Seção P — Educação
  { codigo: '8511-2/00', descricao: 'Educação infantil - creche' },
  { codigo: '8512-1/00', descricao: 'Educação infantil - pré-escola' },
  { codigo: '8513-9/00', descricao: 'Ensino fundamental' },
  { codigo: '8520-1/00', descricao: 'Ensino médio' },
  { codigo: '8531-7/00', descricao: 'Educação superior - graduação' },
  { codigo: '8532-5/00', descricao: 'Educação superior - pós-graduação' },
  { codigo: '8541-4/00', descricao: 'Educação profissional de nível técnico' },
  { codigo: '8542-2/00', descricao: 'Educação profissional de nível tecnológico' },
  { codigo: '8550-3/01', descricao: 'Administração de caixas escolares' },
  { codigo: '8591-1/00', descricao: 'Ensino de esportes' },
  { codigo: '8592-9/01', descricao: 'Ensino de dança' },
  { codigo: '8593-7/00', descricao: 'Ensino de idiomas' },
  { codigo: '8599-6/04', descricao: 'Treinamento em desenvolvimento profissional e gerencial' },
  // Seção Q — Saúde Humana e Serviços Sociais
  { codigo: '8610-1/01', descricao: 'Atividades de atendimento hospitalar, exceto pronto-socorro e unidades para atendimento a urgências' },
  { codigo: '8621-6/01', descricao: 'UTI móvel' },
  { codigo: '8630-5/01', descricao: 'Atividade médica ambulatorial com recursos para a realização de procedimentos cirúrgicos' },
  { codigo: '8630-5/02', descricao: 'Atividade médica ambulatorial com recursos para realização de exames complementares' },
  { codigo: '8630-5/03', descricao: 'Atividade médica ambulatorial restrita a consultas' },
  { codigo: '8630-5/04', descricao: 'Atividade odontológica' },
  { codigo: '8630-5/06', descricao: 'Serviços de vacinação e imunização humana' },
  { codigo: '8630-5/07', descricao: 'Atividades de reprodução humana assistida' },
  { codigo: '8640-2/01', descricao: 'Laboratórios de anatomia patológica e citológica' },
  { codigo: '8640-2/02', descricao: 'Laboratórios clínicos' },
  { codigo: '8640-2/03', descricao: 'Serviços de diálise e nefrologia' },
  { codigo: '8650-0/01', descricao: 'Atividades de enfermagem' },
  { codigo: '8650-0/02', descricao: 'Atividades de profissionais da nutrição' },
  { codigo: '8650-0/03', descricao: 'Atividades de psicologia e psicanálise' },
  { codigo: '8650-0/04', descricao: 'Atividades de fisioterapia' },
  { codigo: '8650-0/05', descricao: 'Atividades de terapia ocupacional' },
  { codigo: '8650-0/06', descricao: 'Atividades de fonoaudiologia' },
  { codigo: '8660-7/00', descricao: 'Atividades de apoio à gestão de saúde' },
  { codigo: '8711-5/01', descricao: 'Clínicas e residências geriátricas' },
  { codigo: '8720-4/01', descricao: 'Atividades de centros de assistência psicossocial' },
  { codigo: '8800-6/00', descricao: 'Serviços de assistência social sem alojamento' },
  // Seção R — Artes, Cultura, Esporte e Recreação
  { codigo: '9001-9/01', descricao: 'Produção teatral' },
  { codigo: '9001-9/02', descricao: 'Produção musical' },
  { codigo: '9001-9/03', descricao: 'Produção de espetáculos de dança' },
  { codigo: '9001-9/06', descricao: 'Atividades de sonorização e de iluminação' },
  { codigo: '9001-9/99', descricao: 'Artes cênicas, espetáculos e atividades complementares não especificadas' },
  { codigo: '9003-5/00', descricao: 'Gestão de espaços para artes cênicas, espetáculos e outras atividades artísticas' },
  { codigo: '9101-5/00', descricao: 'Atividades de bibliotecas e arquivos' },
  { codigo: '9102-3/01', descricao: 'Atividades de museus e de exploração de lugares e prédios históricos e atrações similares' },
  { codigo: '9200-3/01', descricao: 'Casas de bingo' },
  { codigo: '9200-3/99', descricao: 'Exploração de jogos de azar e apostas não especificados' },
  { codigo: '9311-5/00', descricao: 'Gestão de instalações de esportes' },
  { codigo: '9312-3/00', descricao: 'Clubes sociais, esportivos e similares' },
  { codigo: '9313-1/00', descricao: 'Atividades de condicionamento físico' },
  { codigo: '9319-1/01', descricao: 'Produção e promoção de eventos esportivos' },
  { codigo: '9321-2/00', descricao: 'Parques de diversão e parques temáticos' },
  { codigo: '9329-8/01', descricao: 'Discotecas, danceterias, salões de dança e similares' },
  { codigo: '9329-8/99', descricao: 'Outras atividades de recreação e lazer não especificadas' },
  // Seção S — Outras Atividades de Serviços
  { codigo: '9411-1/00', descricao: 'Atividades de organizações associativas patronais e empresariais' },
  { codigo: '9412-0/01', descricao: 'Atividades de fiscalização profissional' },
  { codigo: '9420-1/00', descricao: 'Atividades de organizações sindicais' },
  { codigo: '9430-8/00', descricao: 'Atividades de associações de defesa de direitos sociais' },
  { codigo: '9491-0/00', descricao: 'Atividades de organizações religiosas ou filosóficas' },
  { codigo: '9601-7/01', descricao: 'Lavanderias' },
  { codigo: '9601-7/02', descricao: 'Tinturarias' },
  { codigo: '9602-5/01', descricao: 'Cabeleireiros' },
  { codigo: '9602-5/02', descricao: 'Outras atividades de tratamento de beleza' },
  { codigo: '9603-3/01', descricao: 'Gestão e manutenção de cemitérios' },
  { codigo: '9603-3/02', descricao: 'Serviços de cremação' },
  { codigo: '9603-3/03', descricao: 'Serviços de sepultamento' },
  { codigo: '9603-3/04', descricao: 'Serviços de funerárias' },
  { codigo: '9603-3/05', descricao: 'Serviços de somatoconservação' },
  { codigo: '9609-2/01', descricao: 'Clínicas de estética e similares' },
  { codigo: '9609-2/02', descricao: 'Agências matrimoniais' },
  { codigo: '9609-2/08', descricao: 'Higiene e embelezamento de animais domésticos' },
  { codigo: '9609-2/99', descricao: 'Outras atividades de serviços pessoais não especificadas' },
];
