export interface LC116Item {
  codigo: string;
  descricao: string;
}

export const LC116: LC116Item[] = [
  { codigo: '01.01', descricao: 'Análise e desenvolvimento de sistemas' },
  { codigo: '01.02', descricao: 'Programação' },
  { codigo: '01.03', descricao: 'Processamento, armazenamento ou hospedagem de dados, textos, imagens, vídeos e congêneres' },
  { codigo: '01.04', descricao: 'Elaboração de programas de computadores, inclusive de jogos eletrônicos' },
  { codigo: '01.05', descricao: 'Licenciamento ou cessão de direito de uso de programas de computação' },
  { codigo: '01.06', descricao: 'Assessoria e consultoria em informática' },
  { codigo: '01.07', descricao: 'Suporte técnico em informática, inclusive instalação, configuração e manutenção' },
  { codigo: '01.08', descricao: 'Planejamento, confecção, manutenção e atualização de páginas eletrônicas' },
  { codigo: '01.09', descricao: 'Disponibilização, sem cessão definitiva, de conteúdos de áudio, vídeo, imagem e texto' },
  { codigo: '02.01', descricao: 'Serviços de pesquisas e desenvolvimento de qualquer natureza' },
  { codigo: '03.02', descricao: 'Cessão de direito de uso de marcas e de sinais de propaganda' },
  { codigo: '03.03', descricao: 'Exploração de salões de festas, centro de convenções, escritórios virtuais, stands, quadras esportivas, estádios, ginásios, auditórios, casas de espetáculos, parques de diversões, canchas e congêneres' },
  { codigo: '03.04', descricao: 'Locação, sublocação, arrendamento, direito de passagem ou permissão de uso, compartilhado ou não, de ferrovia, rodovia, postes, cabos, dutos e condutos de qualquer natureza' },
  { codigo: '03.05', descricao: 'Cessão de andaimes, palcos, coberturas e outras estruturas de uso temporário' },
  { codigo: '04.01', descricao: 'Medicina e biomedicina' },
  { codigo: '04.02', descricao: 'Análises clínicas, patologia, eletricidade médica, radioterapia, quimioterapia, ultra-sonografia, ressonância magnética, radiologia, tomografia e congêneres' },
  { codigo: '04.03', descricao: 'Hospitais, clínicas, laboratórios, sanatórios, manicômios, casas de saúde, prontos-socorros, ambulatórios e congêneres' },
  { codigo: '04.04', descricao: 'Instrumentação cirúrgica' },
  { codigo: '04.05', descricao: 'Acupuntura' },
  { codigo: '04.06', descricao: 'Enfermagem, inclusive serviços auxiliares' },
  { codigo: '04.07', descricao: 'Serviços farmacêuticos' },
  { codigo: '04.08', descricao: 'Terapia ocupacional, fisioterapia e fonoaudiologia' },
  { codigo: '04.09', descricao: 'Terapias de qualquer espécie destinadas ao tratamento físico, orgânico e mental' },
  { codigo: '04.10', descricao: 'Nutrição' },
  { codigo: '04.11', descricao: 'Obstetrícia' },
  { codigo: '04.12', descricao: 'Odontologia' },
  { codigo: '04.13', descricao: 'Ortóptica' },
  { codigo: '04.14', descricao: 'Próteses sob encomenda' },
  { codigo: '04.15', descricao: 'Psicanálise' },
  { codigo: '04.16', descricao: 'Psicologia' },
  { codigo: '04.17', descricao: 'Casas de repouso e de recuperação, creches, asilos e congêneres' },
  { codigo: '04.18', descricao: 'Inseminação artificial, fertilização in vitro e congêneres' },
  { codigo: '04.19', descricao: 'Bancos de sangue, leite, pele, olhos, óvulos, sêmen e congêneres' },
  { codigo: '04.20', descricao: 'Coleta de sangue, leite, tecidos, sêmen, órgãos e materiais biológicos de qualquer espécie' },
  { codigo: '04.21', descricao: 'Unidade de atendimento, assistência ou tratamento móvel e congêneres' },
  { codigo: '04.22', descricao: 'Planos de medicina de grupo ou individual e convênios para prestação de assistência médica, hospitalar, odontológica e congêneres' },
  { codigo: '04.23', descricao: 'Outros planos de saúde que se cumpram através de serviços de terceiros contratados, credenciados, cooperados ou apenas pagos pelo operador do plano mediante indicação do beneficiário' },
  { codigo: '05.01', descricao: 'Medicina veterinária e zootecnia' },
  { codigo: '05.02', descricao: 'Hospitais, clínicas, ambulatórios, prontos-socorros e congêneres, na área veterinária' },
  { codigo: '05.03', descricao: 'Laboratórios de análise na área veterinária' },
  { codigo: '05.04', descricao: 'Inseminação artificial, fertilização in vitro e congêneres' },
  { codigo: '05.05', descricao: 'Bancos de sangue e de órgãos e congêneres' },
  { codigo: '05.06', descricao: 'Abate de animais, exceto o abate por venda ao público de aves e suínos' },
  { codigo: '06.01', descricao: 'Barbearia, cabeleireiros, manicuros, pedicuros e congêneres' },
  { codigo: '06.02', descricao: 'Esteticistas, tratamento de pele, depilação e congêneres' },
  { codigo: '06.03', descricao: 'Banhos, duchas, sauna, massagens e congêneres' },
  { codigo: '06.04', descricao: 'Ginástica, dança, esportes, natação, artes marciais e demais atividades físicas' },
  { codigo: '06.05', descricao: 'Centros de emagrecimento, spa e congêneres' },
  { codigo: '06.06', descricao: 'Aplicação de tatuagens, piercings e congêneres' },
  { codigo: '07.01', descricao: 'Engenharia, agronomia, agrimensura, arquitetura, geologia, urbanismo, paisagismo e congêneres' },
  { codigo: '07.02', descricao: 'Execução, por administração, empreitada ou subempreitada, de obras de construção civil, hidráulica ou elétrica e de outras obras semelhantes' },
  { codigo: '07.03', descricao: 'Elaboração de planos diretores, estudos de viabilidade, estudos organizacionais e outros, relacionados com obras e serviços de engenharia' },
  { codigo: '07.04', descricao: 'Demolição' },
  { codigo: '07.05', descricao: 'Reparação, conservação e reforma de edifícios, estradas, pontes, portos e congêneres' },
  { codigo: '07.06', descricao: 'Colocação e instalação de tapetes, carpetes, assoalhos, cortinas, revestimentos de parede, vidros, divisórias, placas de gesso e congêneres' },
  { codigo: '07.07', descricao: 'Recuperação, raspagem, polimento e lustração de pisos e congêneres' },
  { codigo: '07.08', descricao: 'Calafetação' },
  { codigo: '07.09', descricao: 'Varrição, coleta, remoção, incineração, tratamento, reciclagem, separação e destinação final de lixo, rejeitos e outros resíduos quaisquer' },
  { codigo: '07.10', descricao: 'Limpeza, manutenção e conservação de vias e logradouros públicos, imóveis, chaminés, piscinas, parques, jardins e congêneres' },
  { codigo: '07.11', descricao: 'Decoração e jardinagem, inclusive corte e poda de árvores' },
  { codigo: '07.12', descricao: 'Controle e tratamento de efluentes de qualquer natureza e de agentes físicos, químicos e biológicos' },
  { codigo: '07.13', descricao: 'Dedetização, desinfecção, desinsetização, imunização, higienização, desratização, pulverização e congêneres' },
  { codigo: '07.16', descricao: 'Florestamento, reflorestamento, semeadura, adubação, reparação de solo, plantio, silagem, colheita, corte e descascamento de árvores, silvicultura, exploração florestal e dos serviços congêneres' },
  { codigo: '07.17', descricao: 'Escoramento, contenção de encostas e serviços congêneres' },
  { codigo: '07.18', descricao: 'Limpeza e dragagem de rios, portos, canais, baías, lagos, lagoas, represas, açudes e congêneres' },
  { codigo: '07.19', descricao: 'Acompanhamento e fiscalização da execução de obras de engenharia, arquitetura e urbanismo' },
  { codigo: '07.20', descricao: 'Aerofotogrametria (inclusive interpretação), cartografia, mapeamento, levantamentos topográficos, batimétricos, geográficos, geodésicos, geológicos, geofísicos e congêneres' },
  { codigo: '07.21', descricao: 'Pesquisa, perfuração, cimentação, mergulho, perfilagem, concretação, testemunhagem, pescaria, canhoneio, afundamento e outros serviços relacionados com a exploração e explotação de petróleo, gás natural e de outros recursos minerais' },
  { codigo: '07.22', descricao: 'Nucleação e bombardeamento de nuvens e congêneres' },
  { codigo: '08.01', descricao: 'Ensino regular pré-escolar, fundamental, médio e superior' },
  { codigo: '08.02', descricao: 'Instrução, treinamento, orientação pedagógica e educacional, avaliação de conhecimentos de qualquer natureza' },
  { codigo: '09.01', descricao: 'Hospedagem de qualquer natureza em hotéis, apart-service condominiais, flat, apart-hotéis, hotéis residência, residence-service, suite service, hotelaria marítima' },
  { codigo: '09.02', descricao: 'Agenciamento, organização, promoção, intermediação e execução de programas de turismo, passeios, viagens, excursões, hospedagens e congêneres' },
  { codigo: '09.03', descricao: 'Guias de turismo' },
  { codigo: '10.01', descricao: 'Agenciamento, corretagem ou intermediação de câmbio, de seguros, de cartões de crédito, de planos de saúde e de planos de previdência privada' },
  { codigo: '10.02', descricao: 'Agenciamento, corretagem ou intermediação de títulos em geral, valores mobiliários e contratos quaisquer' },
  { codigo: '10.03', descricao: 'Agenciamento, corretagem ou intermediação de direitos de propriedade industrial, artística ou literária' },
  { codigo: '10.04', descricao: 'Agenciamento, corretagem ou intermediação de contratos de arrendamento mercantil (leasing), bem como da compra e venda de bens móveis, semoventes, produtos de origem animal ou vegetal' },
  { codigo: '10.05', descricao: 'Agenciamento, corretagem ou intermediação de bens imóveis e serviços afins' },
  { codigo: '10.06', descricao: 'Agenciamento marítimo' },
  { codigo: '10.07', descricao: 'Agenciamento de notícias' },
  { codigo: '10.08', descricao: 'Agenciamento de publicidade e propaganda, inclusive o agenciamento de veiculação por quaisquer meios' },
  { codigo: '10.09', descricao: 'Representação de qualquer natureza, inclusive comercial' },
  { codigo: '10.10', descricao: 'Distribuição de bens de terceiros' },
  { codigo: '11.01', descricao: 'Guarda e estacionamento de veículos terrestres automotores, de aeronaves e de embarcações' },
  { codigo: '11.02', descricao: 'Vigilância, segurança ou monitoramento de bens, pessoas e semoventes' },
  { codigo: '11.03', descricao: 'Escolta, inclusive de veículos e cargas' },
  { codigo: '11.04', descricao: 'Armazenamento, depósito, carga, descarga, arrumação e guarda de bens de qualquer espécie' },
  { codigo: '12.01', descricao: 'Espetáculos teatrais' },
  { codigo: '12.02', descricao: 'Exibição de filmes, entrevistas, musicais, espetáculos, shows, ballet, danças, desfiles, bailes, óperas, concertos, recitais, festivais e congêneres' },
  { codigo: '12.03', descricao: 'Espetáculos circenses' },
  { codigo: '12.04', descricao: 'Programas de auditório' },
  { codigo: '12.05', descricao: 'Parques de diversões, centros de lazer e congêneres' },
  { codigo: '12.06', descricao: 'Boates, taxi-dancing e congêneres' },
  { codigo: '12.07', descricao: 'Shows, ballet, danças, desfiles, bailes, óperas, concertos, recitais, festivais e congêneres' },
  { codigo: '12.08', descricao: 'Feiras, exposições, congressos e congêneres' },
  { codigo: '12.09', descricao: 'Bilhares, boliches e outros jogos recreativos' },
  { codigo: '12.10', descricao: 'Corridas e competições de animais' },
  { codigo: '12.11', descricao: 'Competições esportivas ou de destreza física ou intelectual, com ou sem a participação do espectador' },
  { codigo: '12.12', descricao: 'Execução de música' },
  { codigo: '12.13', descricao: 'Produção, mediante ou sem encomenda prévia, de eventos, espetáculos, entrevistas, shows, ballet, danças, desfiles, bailes, teatros, óperas, concertos, recitais, festivais e congêneres' },
  { codigo: '12.14', descricao: 'Fornecimento de música para ambientes fechados ou não, mediante transmissão por qualquer processo' },
  { codigo: '12.15', descricao: 'Desfiles de blocos carnavalescos ou folclóricos, trios elétricos e congêneres' },
  { codigo: '12.16', descricao: 'Exibição de filmes, entrevistas, musicais, espetáculos, shows, ballet, danças, desfiles, bailes, óperas, concertos, recitais, festivais e congêneres' },
  { codigo: '12.17', descricao: 'Recreação e animação, inclusive em festas e eventos de qualquer natureza' },
  { codigo: '13.02', descricao: 'Fonografia ou gravação de sons, inclusive trucagem, dublagem, mixagem e congêneres' },
  { codigo: '13.03', descricao: 'Fotografia e cinematografia, inclusive revelação, ampliação, cópia, reprodução, trucagem e congêneres' },
  { codigo: '13.04', descricao: 'Reprografia, microfilmagem e digitalização' },
  { codigo: '13.05', descricao: 'Composição gráfica, inclusive confecção de impressos gráficos, fotocomposição, clicheria, zincografia, litografia e fotolitografia' },
  { codigo: '14.01', descricao: 'Lubrificação, limpeza, lustração, revisão, carga e recarga, conserto, restauração, blindagem, manutenção e conservação de máquinas, veículos, aparelhos, equipamentos, motores, elevadores ou de qualquer objeto' },
  { codigo: '14.02', descricao: 'Assistência técnica' },
  { codigo: '14.03', descricao: 'Recondicionamento de motores (exceto peças e partes empregadas, que ficam sujeitas ao ICMS)' },
  { codigo: '14.04', descricao: 'Recauchutagem ou regeneração de pneus' },
  { codigo: '14.05', descricao: 'Restauração, recondicionamento, acondicionamento, pintura, beneficiamento, lavagem, secagem, tingimento, galvanoplastia, anodização, corte, recorte, plastificação, costura, acabamento, polimento e congêneres de objetos quaisquer' },
  { codigo: '14.06', descricao: 'Instalação e montagem de aparelhos, máquinas e equipamentos, inclusive montagem industrial, prestados ao usuário final, exclusivamente com material por ele fornecido' },
  { codigo: '14.07', descricao: 'Colocação de molduras e congêneres' },
  { codigo: '14.08', descricao: 'Encadernação, gravação e douração de livros, revistas e congêneres' },
  { codigo: '14.09', descricao: 'Alfaiataria e costura, quando o material for fornecido pelo usuário final, exceto aviamento' },
  { codigo: '14.10', descricao: 'Tinturaria e lavanderia' },
  { codigo: '14.11', descricao: 'Tapeçaria e reforma de estofamentos em geral' },
  { codigo: '14.12', descricao: 'Funilaria e lanternagem' },
  { codigo: '14.13', descricao: 'Carpintaria e serralheria' },
  { codigo: '14.14', descricao: 'Guincho intramunicipal, guindaste e içamento' },
  { codigo: '15.01', descricao: 'Administração de fundos quaisquer, exceto os prestados por instituições autorizadas a funcionar pelo Banco Central do Brasil' },
  { codigo: '15.02', descricao: 'Abertura de contas em geral, inclusive conta-corrente, conta de investimentos e aplicação e caderneta de poupança, no País e no exterior' },
  { codigo: '15.03', descricao: 'Locação e manutenção de cofres particulares, de terminais eletrônicos, de terminais de atendimento e de bens e equipamentos em geral' },
  { codigo: '15.04', descricao: 'Fornecimento ou emissão de atestados em geral, inclusive atestado de idoneidade, atestado de capacidade financeira e congêneres' },
  { codigo: '15.05', descricao: 'Cadastro, elaboração de ficha cadastral, renovação cadastral e congêneres, inclusive o fornecimento de certificado e atestado' },
  { codigo: '15.06', descricao: 'Emissão, reemissão e fornecimento de avisos, comprovantes e documentos em geral; abrangidos todos os serviços relacionados com os documentos emitidos, exceto os serviços previstos no item 15.08' },
  { codigo: '15.07', descricao: 'Acesso, movimentação, atendimento e consulta a contas em geral, por qualquer meio ou processo, inclusive por telefone, fac-símile, internet e telex' },
  { codigo: '15.08', descricao: 'Emissão, reemissão, alteração, cessão, substituição, cancelamento e registro de contrato de crédito; inclusive operações realizadas por intermédio de cartão-crédito ou similar' },
  { codigo: '15.09', descricao: 'Arrendamento mercantil (leasing) de quaisquer bens, inclusive cessão de direitos e obrigações, substituição de garantia, alteração, cancelamento e registro de contrato' },
  { codigo: '15.10', descricao: 'Serviços relacionados a cobranças, recebimentos ou pagamentos em geral, de títulos quaisquer, de contas ou carnês, de câmbio, de tributos e por conta de terceiros' },
  { codigo: '15.11', descricao: 'Devolução de títulos, protesto de títulos, sustação de protesto, manutenção de títulos, reapresentação de títulos, e demais serviços a eles relacionados' },
  { codigo: '15.12', descricao: 'Custódia em geral, inclusive de títulos e valores mobiliários' },
  { codigo: '15.13', descricao: 'Serviços relacionados a operações de câmbio em geral, edição, alteração, prorrogação, cancelamento e baixa de contrato de câmbio' },
  { codigo: '15.14', descricao: 'Avaliação de bens e serviços de qualquer natureza' },
  { codigo: '15.15', descricao: 'Emissão, negociação, reemissão, liquidação, planejamento e cancelamento de títulos patrimoniais, de capitalização e de previdência privada' },
  { codigo: '15.16', descricao: 'Operações de câmbio, compra e venda de moeda estrangeira para entrega imediata ou a prazo' },
  { codigo: '15.17', descricao: 'Emissão, fornecimento, cancelamento, uso, alteração, transmissão, bloqueio e renovação de cartão magnético, cartão de crédito, cartão de débito, cartão salário e congêneres' },
  { codigo: '15.18', descricao: 'Serviços relacionados a crédito imobiliário, avaliação e vistoria de imóvel ou obra' },
  { codigo: '16.01', descricao: 'Serviços de transporte de natureza municipal' },
  { codigo: '17.01', descricao: 'Assessoria ou consultoria de qualquer natureza, não contida em outros itens desta lista' },
  { codigo: '17.02', descricao: 'Análise, exame, pesquisa, coleta, compilação e fornecimento de dados e informações de qualquer natureza, inclusive cadastro e similares' },
  { codigo: '17.03', descricao: 'Planejamento, coordenação, programação ou organização técnica, financeira ou administrativa' },
  { codigo: '17.04', descricao: 'Recrutamento, agenciamento, seleção e colocação de mão-de-obra' },
  { codigo: '17.05', descricao: 'Fornecimento de mão-de-obra, mesmo em caráter temporário, inclusive de empregados ou trabalhadores, avulsos ou temporários' },
  { codigo: '17.06', descricao: 'Propaganda e publicidade, inclusive promoção de vendas, planejamento de campanhas ou sistemas de publicidade, elaboração de desenhos, textos e demais materiais publicitários' },
  { codigo: '17.07', descricao: 'Franquia (franchising)' },
  { codigo: '17.08', descricao: 'Perícias, laudos, exames técnicos e análises técnicas' },
  { codigo: '17.09', descricao: 'Planejamento, organização e administração de feiras, exposições, congressos e congêneres' },
  { codigo: '17.10', descricao: 'Organização de festas e recepções; bufê (exceto o fornecimento de alimentação e bebidas, que fica sujeito ao ICMS)' },
  { codigo: '17.11', descricao: 'Administração em geral, inclusive de bens e negócios de terceiros' },
  { codigo: '17.12', descricao: 'Leilão e congêneres' },
  { codigo: '17.13', descricao: 'Advocacia' },
  { codigo: '17.14', descricao: 'Arbitragem de qualquer espécie, inclusive jurídica' },
  { codigo: '17.15', descricao: 'Auditoria' },
  { codigo: '17.16', descricao: 'Análise de Organização e Métodos' },
  { codigo: '17.17', descricao: 'Atuária e cálculos técnicos de qualquer natureza' },
  { codigo: '17.18', descricao: 'Contabilidade, inclusive serviços técnicos e auxiliares' },
  { codigo: '17.19', descricao: 'Consultoria e assessoria econômica ou financeira' },
  { codigo: '17.20', descricao: 'Estatística' },
  { codigo: '17.21', descricao: 'Cobrança em geral' },
  { codigo: '17.22', descricao: 'Assessoria, análise, avaliação, atendimento, consulta, cadastro, seleção, gerenciamento de informações, administração de contas a receber ou a pagar e em geral, relacionados a operações de faturização (factoring)' },
  { codigo: '17.23', descricao: 'Apresentação de palestras, conferências, seminários e congêneres' },
  { codigo: '17.24', descricao: 'Inserção de textos, desenhos e outros materiais de propaganda e publicidade, em qualquer meio (exceto em livros, jornais, periódicos e nas modalidades de serviços de radiodifusão sonora e de sons e imagens de recepção livre e gratuita)' },
  { codigo: '18.01', descricao: 'Serviços de regulação de sinistros vinculados a contratos de seguros; inspeção e avaliação de riscos para cobertura de contratos de seguros' },
  { codigo: '18.02', descricao: 'Prevenção e gerência de riscos seguráveis e congêneres' },
  { codigo: '19.01', descricao: 'Serviços de distribuição e venda de bilhetes e demais produtos de loteria, bingos, cartões, pules ou cupons de apostas, sorteios, prêmios, inclusive os decorrentes de títulos de capitalização e congêneres' },
  { codigo: '20.01', descricao: 'Serviços portuários, ferroportuários, utilização de porto, movimentação de passageiros, reboque de embarcações, rebocador escoteiro, atracação, desatracação, serviços de praticagem, capatazia, armazenagem de qualquer natureza, serviços acessórios, movimentação de mercadorias, serviços de apoio marítimo, de movimentação ao largo, serviços de armadores, estiva, conferência, logística e congêneres' },
  { codigo: '20.02', descricao: 'Serviços aeroportuários, utilização de aeroporto, movimentação de passageiros, armazenagem de qualquer natureza, capatazia, movimentação de aeronaves, serviços de apoio aeroportuários, serviços acessórios, movimentação de mercadorias, logística e congêneres' },
  { codigo: '20.03', descricao: 'Serviços de terminais rodoviários e ferroviários, utilização de terminais rodoviários e ferroviários, movimentação de passageiros, mercadorias, inclusive suas operações, logística e congêneres' },
  { codigo: '21.01', descricao: 'Serviços de registros públicos, cartorários e notariais' },
  { codigo: '22.01', descricao: 'Serviços de exploração de rodovias mediante cobrança de preço ou pedágio dos usuários, envolvendo execução de serviços de conservação, manutenção, melhoramentos para adequação de capacidade e segurança de trânsito, operação, monitoração, assistência aos usuários e outros serviços definidos em contratos, atos de concessão ou de permissão ou em normas oficiais' },
  { codigo: '23.01', descricao: 'Serviços de programação e comunicação visual, desenho industrial e congêneres' },
  { codigo: '24.01', descricao: 'Serviços de chaveiros, confecção de carimbos, placas, sinalização visual, banners, adesivos e congêneres' },
  { codigo: '25.01', descricao: 'Funerais, inclusive fornecimento de caixão, urna ou esquifes; aluguel de capela; transporte do corpo cadavérico; fornecimento de flores, coroas e outros paramentos; desembaraço de certidão de óbito' },
  { codigo: '25.02', descricao: 'Embalsamamento, embalsamento, cremação, incineração e congêneres' },
  { codigo: '25.03', descricao: 'Planos ou convênio funerários' },
  { codigo: '25.04', descricao: 'Manutenção e conservação de jazigos e cemitérios' },
  { codigo: '25.05', descricao: 'Cessão de uso de espaços em cemitérios para sepultamento' },
  { codigo: '26.01', descricao: 'Serviços de coleta, remessa ou entrega de correspondências, documentos, objetos, bens ou valores, inclusive pelos correios e suas agências franqueadas; courrier e congêneres' },
  { codigo: '27.01', descricao: 'Serviços de assistência social' },
  { codigo: '28.01', descricao: 'Serviços de avaliação de bens e serviços de qualquer natureza' },
  { codigo: '29.01', descricao: 'Serviços de biblioteconomia' },
  { codigo: '30.01', descricao: 'Biologia e biotecnologia' },
  { codigo: '31.01', descricao: 'Serviços técnicos em edificações, eletrônica, eletrotécnica, mecânica, telecomunicações e congêneres' },
  { codigo: '32.01', descricao: 'Serviços de desenhos técnicos' },
  { codigo: '33.01', descricao: 'Serviços de desembaraço aduaneiro, comissários, despachantes e congêneres' },
  { codigo: '34.01', descricao: 'Serviços de investigações particulares, detetives e congêneres' },
  { codigo: '35.01', descricao: 'Serviços de reportagem, assessoria de imprensa, jornalismo e relações públicas' },
  { codigo: '36.01', descricao: 'Serviços de meteorologia' },
  { codigo: '37.01', descricao: 'Serviços de artistas, atletas, modelos e manequins' },
  { codigo: '38.01', descricao: 'Serviços de museologia' },
  { codigo: '39.01', descricao: 'Serviços de ourivesaria e lapidação (quando o material for fornecido pelo tomador do serviço)' },
  { codigo: '40.01', descricao: 'Obras de arte sob encomenda' },
];
