export interface NBSItem {
  codigo: string;
  descricao: string;
}

export const NBS: NBSItem[] = [
  { codigo: '1.0101', descricao: 'Serviços de apoio ao cultivo de vegetais' },
  { codigo: '1.0102', descricao: 'Serviços de apoio à criação de animais' },
  { codigo: '1.0103', descricao: 'Serviços de apoio à exploração florestal' },
  { codigo: '1.0104', descricao: 'Serviços de apoio à pesca e aquicultura' },
  { codigo: '1.0201', descricao: 'Serviços de lavra e mineração' },
  { codigo: '1.0301', descricao: 'Serviços de construção de edifícios residenciais' },
  { codigo: '1.0302', descricao: 'Serviços de construção de edifícios não residenciais' },
  { codigo: '1.0303', descricao: 'Serviços de construção de rodovias, pontes, túneis e portos' },
  { codigo: '1.0304', descricao: 'Serviços de construção de redes de distribuição de energia elétrica e de telecomunicações' },
  { codigo: '1.0305', descricao: 'Serviços de construção de redes de água, esgoto e gás' },
  { codigo: '1.0399', descricao: 'Outros serviços de construção' },
  { codigo: '1.0401', descricao: 'Serviços de análise e desenvolvimento de sistemas' },
  { codigo: '1.0402', descricao: 'Serviços de programação de computadores' },
  { codigo: '1.0403', descricao: 'Serviços de processamento de dados e hospedagem' },
  { codigo: '1.0404', descricao: 'Serviços de suporte técnico em TI' },
  { codigo: '1.0405', descricao: 'Serviços de manutenção de hardware' },
  { codigo: '1.0406', descricao: 'Serviços de licenciamento de software' },
  { codigo: '1.0407', descricao: 'Serviços de segurança da informação' },
  { codigo: '1.0408', descricao: 'Serviços de cloud computing' },
  { codigo: '1.0409', descricao: 'Serviços de consultoria em tecnologia da informação' },
  { codigo: '1.0499', descricao: 'Outros serviços de tecnologia da informação' },
  { codigo: '1.0501', descricao: 'Serviços de pesquisa e desenvolvimento em ciências naturais' },
  { codigo: '1.0502', descricao: 'Serviços de pesquisa e desenvolvimento em ciências sociais' },
  { codigo: '1.0601', descricao: 'Serviços de venda por atacado — comissionamento e corretagem' },
  { codigo: '1.0701', descricao: 'Serviços de transporte rodoviário de cargas' },
  { codigo: '1.0702', descricao: 'Serviços de transporte rodoviário de passageiros' },
  { codigo: '1.0703', descricao: 'Serviços de transporte ferroviário' },
  { codigo: '1.0704', descricao: 'Serviços de transporte aquaviário' },
  { codigo: '1.0705', descricao: 'Serviços de transporte aéreo de cargas' },
  { codigo: '1.0706', descricao: 'Serviços de transporte aéreo de passageiros' },
  { codigo: '1.0799', descricao: 'Outros serviços de transporte' },
  { codigo: '1.0801', descricao: 'Serviços de armazenagem e depósito' },
  { codigo: '1.0802', descricao: 'Serviços auxiliares de transporte' },
  { codigo: '1.0803', descricao: 'Serviços postais e de entrega de encomendas' },
  { codigo: '1.0901', descricao: 'Serviços de hospedagem em hotéis' },
  { codigo: '1.0902', descricao: 'Serviços de hospedagem em apart-hotéis e flats' },
  { codigo: '1.0903', descricao: 'Serviços de hospedagem em albergues e similares' },
  { codigo: '1.1001', descricao: 'Serviços de restaurantes e lanchonetes' },
  { codigo: '1.1002', descricao: 'Serviços de fornecimento de alimentos e bebidas em eventos' },
  { codigo: '1.1101', descricao: 'Serviços de publicação de livros e periódicos' },
  { codigo: '1.1102', descricao: 'Serviços de produção cinematográfica e de vídeo' },
  { codigo: '1.1103', descricao: 'Serviços de radiodifusão e de televisão' },
  { codigo: '1.1104', descricao: 'Serviços de telecomunicações' },
  { codigo: '1.1105', descricao: 'Serviços de transmissão de dados e internet' },
  { codigo: '1.1201', descricao: 'Serviços de intermediação financeira' },
  { codigo: '1.1202', descricao: 'Serviços de seguros e resseguros' },
  { codigo: '1.1203', descricao: 'Serviços de previdência complementar' },
  { codigo: '1.1204', descricao: 'Serviços auxiliares de intermediação financeira' },
  { codigo: '1.1301', descricao: 'Serviços imobiliários' },
  { codigo: '1.1302', descricao: 'Serviços de locação e arrendamento' },
  { codigo: '1.1401', descricao: 'Serviços jurídicos' },
  { codigo: '1.1402', descricao: 'Serviços de contabilidade e auditoria' },
  { codigo: '1.1403', descricao: 'Serviços de consultoria empresarial e de gestão' },
  { codigo: '1.1404', descricao: 'Serviços de engenharia e arquitetura' },
  { codigo: '1.1405', descricao: 'Serviços de publicidade e propaganda' },
  { codigo: '1.1406', descricao: 'Serviços de pesquisa de mercado' },
  { codigo: '1.1407', descricao: 'Serviços de relações públicas' },
  { codigo: '1.1408', descricao: 'Serviços de design e comunicação visual' },
  { codigo: '1.1499', descricao: 'Outros serviços profissionais, científicos e técnicos' },
  { codigo: '1.1501', descricao: 'Serviços de locação de veículos automotores sem condutor' },
  { codigo: '1.1502', descricao: 'Serviços de locação de outros meios de transporte sem tripulante' },
  { codigo: '1.1503', descricao: 'Serviços de locação de máquinas e equipamentos sem operador' },
  { codigo: '1.1601', descricao: 'Serviços de emprego' },
  { codigo: '1.1602', descricao: 'Serviços de segurança e investigação' },
  { codigo: '1.1603', descricao: 'Serviços de limpeza e conservação' },
  { codigo: '1.1604', descricao: 'Serviços de agenciamento de viagens e turismo' },
  { codigo: '1.1605', descricao: 'Serviços de apoio administrativo e secretarial' },
  { codigo: '1.1699', descricao: 'Outros serviços administrativos' },
  { codigo: '1.1701', descricao: 'Serviços de educação infantil' },
  { codigo: '1.1702', descricao: 'Serviços de ensino fundamental' },
  { codigo: '1.1703', descricao: 'Serviços de ensino médio' },
  { codigo: '1.1704', descricao: 'Serviços de ensino superior' },
  { codigo: '1.1705', descricao: 'Serviços de educação técnica e profissional' },
  { codigo: '1.1706', descricao: 'Serviços de cursos de idiomas' },
  { codigo: '1.1799', descricao: 'Outros serviços de educação' },
  { codigo: '1.1801', descricao: 'Serviços hospitalares' },
  { codigo: '1.1802', descricao: 'Serviços médicos e odontológicos' },
  { codigo: '1.1803', descricao: 'Serviços de diagnóstico e análises clínicas' },
  { codigo: '1.1804', descricao: 'Serviços de fisioterapia e terapias em geral' },
  { codigo: '1.1805', descricao: 'Serviços de assistência social' },
  { codigo: '1.1899', descricao: 'Outros serviços de saúde' },
  { codigo: '1.1901', descricao: 'Serviços de saneamento e gestão de resíduos' },
  { codigo: '1.2001', descricao: 'Serviços de artes cênicas' },
  { codigo: '1.2002', descricao: 'Serviços de produção de eventos e entretenimento' },
  { codigo: '1.2003', descricao: 'Serviços esportivos' },
  { codigo: '1.2004', descricao: 'Serviços de recreação e lazer' },
  { codigo: '1.2099', descricao: 'Outros serviços culturais e de entretenimento' },
  { codigo: '1.2101', descricao: 'Serviços de reparação e manutenção de veículos automotores' },
  { codigo: '1.2102', descricao: 'Serviços de reparação de bens pessoais e domésticos' },
  { codigo: '1.2103', descricao: 'Serviços de lavanderia' },
  { codigo: '1.2104', descricao: 'Serviços pessoais de beleza e higiene' },
  { codigo: '1.2105', descricao: 'Serviços funerários' },
  { codigo: '1.2199', descricao: 'Outros serviços pessoais' },
  { codigo: '2.0101', descricao: 'Serviços de construção no exterior' },
  { codigo: '2.0201', descricao: 'Serviços de tecnologia da informação prestados ao exterior' },
  { codigo: '2.0301', descricao: 'Serviços financeiros prestados ao exterior' },
  { codigo: '2.0401', descricao: 'Serviços profissionais prestados ao exterior' },
  { codigo: '2.0501', descricao: 'Serviços de transporte internacional' },
];
